//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TobeDemo.TobeServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="TobeServices", ConfigurationName="TobeServices.TobeService1Soap")]
    public interface TobeService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="TobeServices/Multiply", ReplyAction="*")]
        int Multiply(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="TobeServices/Multiply", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MultiplyAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="TobeServices/SubstractMathAbs", ReplyAction="*")]
        int SubstractMathAbs(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="TobeServices/SubstractMathAbs", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubstractMathAbsAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TobeService1SoapChannel : TobeDemo.TobeServices.TobeService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TobeService1SoapClient : System.ServiceModel.ClientBase<TobeDemo.TobeServices.TobeService1Soap>, TobeDemo.TobeServices.TobeService1Soap {
        
        public TobeService1SoapClient() {
        }
        
        public TobeService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TobeService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TobeService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TobeService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Multiply(int a, int b) {
            return base.Channel.Multiply(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyAsync(int a, int b) {
            return base.Channel.MultiplyAsync(a, b);
        }
        
        public int SubstractMathAbs(int a, int b) {
            return base.Channel.SubstractMathAbs(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SubstractMathAbsAsync(int a, int b) {
            return base.Channel.SubstractMathAbsAsync(a, b);
        }
    }
}
