'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class PlanetWroxEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=PlanetWroxEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Genres() As DbSet(Of Genre)
    Public Overridable Property Reviews() As DbSet(Of Review)
    Public Overridable Property PhotoAlbums() As DbSet(Of PhotoAlbum)
    Public Overridable Property Pictures() As DbSet(Of Picture)

End Class
